const store = require('../../utils/store');
Page({ data: { aid: '', name: '', season: '', code: '', role: '', stats: {}, players: [], records: [], showRec: false, showPlayer: false, rec: {}, newPlayerName: '', selPid: '' },
  onLoad(o) { this.setData({ aid: o.id, name: decodeURIComponent(o.name || ''), season: decodeURIComponent(o.season || ''), code: o.code || '', role: o.role || 'member' }); wx.setNavigationBarTitle({ title: o.name ? decodeURIComponent(o.name) : '同盟' }); this.load(); },
  onShow() { if (this.data.aid) this.load(); },
  async load() { const aid = this.data.aid; const [players, records] = await Promise.all([store.players.list(aid), store.records.list(aid)]); const byP = {}; (records || []).forEach(r => { (byP[r.player_id] = byP[r.player_id] || []).push(r); }); const roster = (players || []).map(p => { const rs = (byP[p.id] || []).sort((a, b) => new Date(a.recorded_at) - new Date(b.recorded_at)); const last = rs.length ? rs[rs.length - 1] : null; return { id: p.id, game_name: p.game_name, team: p.team || '', duty: p.duty || '', count: rs.length, merit: last ? last.merit : 0, power: last ? last.power : 0, ct: last ? last.contribution_total : 0, cw: last ? last.contribution_week : 0 }; }); const stats = { players: (players || []).length, records: (records || []).length, topMerit: Math.max.apply(null, roster.map(x => x.merit).concat([0])), topPower: Math.max.apply(null, roster.map(x => x.power).concat([0])) }; this.setData({ players: roster, records: records || [], stats: stats }); },
  addRecord(e) { const p = this.data.players[e.currentTarget.dataset.i]; this.setData({ showRec: true, selPid: p.id, rec: { name: p.game_name, merit: '', power: '', ct: '', cw: '' } }); },
  closeRec() { this.setData({ showRec: false }); }, onRec(e) { const k = e.currentTarget.dataset.k; this.setData({ ['rec.' + k]: e.detail.value }); },
  async saveRec() { const r = this.data.rec; const pid = this.data.selPid; try { await store.records.add(this.data.aid, { player_id: pid, merit: r.merit, power: r.power, contribution_total: r.ct, contribution_week: r.cw, source: 'manual' }); this.setData({ showRec: false }); wx.showToast({ title: '已保存', icon: 'success' }); this.load(); } catch (e) { wx.showToast({ title: e.message, icon: 'none' }); } },
  openAddPlayer() { this.setData({ showPlayer: true, newPlayerName: '' }); }, closePlayer() { this.setData({ showPlayer: false }); }, onNewPlayer(e) { this.setData({ newPlayerName: e.detail.value }); },
  async savePlayer() { const n = (this.data.newPlayerName || '').trim(); if (!n) { wx.showToast({ title: '请输入昵称', icon: 'none' }); return; } try { await store.players.add(this.data.aid, { game_name: n, team: '', duty: '' }); this.setData({ showPlayer: false }); wx.showToast({ title: '已添加', icon: 'success' }); this.load(); } catch (e) { wx.showToast({ title: e.message, icon: 'none' }); } },
  chooseImage() { wx.chooseMedia({ count: 1, mediaType: ['image'], sourceType: ['album', 'camera'], success: async (res) => { wx.showLoading({ title: '识别中…' }); try { const out = await store.vision.recognize(res.tempFiles[0].tempFilePath); wx.hideLoading(); const j = out.json; if (Array.isArray(j) && j.length) { const r = j[0]; this.setData({ showRec: true, rec: { name: r.name || '', merit: r.merit || '', power: r.power || '', ct: r.contributionTotal || '', cw: r.contributionWeek || '' } }); wx.showToast({ title: '识别到 ' + j.length + ' 人，已取第一行', icon: 'none' }); } else if (j && !Array.isArray(j)) { this.setData({ showRec: true, rec: { name: '', merit: j.merit || '', power: j.power || '', ct: j.contributionTotal || '', cw: j.contributionWeek || '' } }); wx.showToast({ title: '识别完成，请选择玩家', icon: 'none' }); } else { wx.showToast({ title: '未识别到数据', icon: 'none' }); } } catch (e) { wx.hideLoading(); wx.showToast({ title: e.message, icon: 'none' }); } } }); },
  pickPlayer(e) { const i = e.detail.value; const p = this.data.players[i]; this.setData({ selPid: p.id, 'rec.name': p.game_name }); }
});
